import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: src/main.ts
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // Settings-defaults files (Dungeon Cartographer Settings/*.md, *.base) are
  // imported as raw text and baked into main.js - see settingsDefaults.ts.
  // Needed because BRAT and Obsidian's own installer only ever fetch
  // main.js/manifest.json/styles.css from a release, never any sibling
  // folder shipped alongside them (confirmed against BRAT's dev guide,
  // 2026-09-18) - a plain on-disk defaults folder only worked in the dev
  // vault, where this repo happens to be checked out directly into the
  // installed plugin's own folder.
  loader: { ".md": "text", ".base": "text" },
  // 2026-09-05: `three` used to be bundled in here (the dungeon view was a
  // Three.js scene) - it's gone now that the view is a flat SVG renderer,
  // see "2D Rendering Plan.md" rollout step 6. Only the Obsidian runtime +
  // node/electron stay external.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  // Build in place — this config lives inside the plugin folder Obsidian loads.
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
